#include <Arduino.h>
#include "CommandManager.hpp"
#include "IODebouncer.h"
#include "PamiHardware.hpp"
#include "TestManager.hpp"
#include "PamIA.hpp"
#include "AsservManager.hpp"
#include "Chrono.hpp"
#include "DetectionManager.hpp"
#include "RoadMap.hpp"
#include <vector>
#include <ESP32Servo.h>

#define PIN_LIDAR_PWM 18
#define PWM_CHANNEL 0
#define PWM_FREQ 1000
#define PWM_RESOLUTION 10

#define UART_PC_SPEED 115200
#define UART_NUCLEO 115200

#define IO_DEBOUNCE_PERIOD 5

#define IO_ID_TIRETTE 0
#define IO_ID_COULEUR 1
#define IO_ID_GRPIO_1 2
#define IO_ID_GRPIO_2 3
#define IO_ID_GPIO_SERVO_01 4
#define IO_ID_GPIO_SERVO_02 5
#define IO_I2C_SDA 8
#define IO_I2C_SCL 7

#define STOP_MOVING_MS 100000 // TODO valeurs de test
#define DETECTION_THRESHOLD_CM 13

// Temps à attendre entre l'enlèvement de la tirette et le démarrage des PAMIs 
#define PAMI_START_WAIT_TIME 85000

#define SERVO_POS_LOW 10
#define SERVO_POS_HIGH 170
#define SERVO_OSCILLATION_PERIOD 800

#define PAMI_STAR_SRF_CODE 127
#define PAMI_GROUPIE_1_SRF_CODE 254
#define PAMI_GROUPIE_2_SRF_CODE 253
#define PAMI_GROUPIE_3_SRF_CODE 251

// Pour chaque PAMI, on associe une feuille de route à une adresse de SRF08
// RoadMapItem { command, x, y, angle, detectionThresholdOrPeriod }

std::vector<RoadMap> roadMaps = {
  // GROUPIE 1
  RoadMap(PAMI_GROUPIE_1_SRF_CODE, PAMIA_COLOR::YELLOW, {
    {ROADMAP_COMMAND::CELEBRATE, SERVO_POS_LOW, SERVO_POS_HIGH, 0, SERVO_OSCILLATION_PERIOD},
    {ROADMAP_COMMAND::SET_POSITION, 170, 80, 1.57079632679, 0},
    {ROADMAP_COMMAND::WAIT, PAMI_START_WAIT_TIME + 4000, 0, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 170, 180, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 550, 1000, 0, DETECTION_THRESHOLD_CM},
  }),
  RoadMap(PAMI_GROUPIE_1_SRF_CODE, PAMIA_COLOR::BLUE, {
    {ROADMAP_COMMAND::CELEBRATE, SERVO_POS_LOW, SERVO_POS_HIGH, 0, SERVO_OSCILLATION_PERIOD},
    {ROADMAP_COMMAND::SET_POSITION, 170, 2920, -1.57079632679, 0},
    {ROADMAP_COMMAND::WAIT, PAMI_START_WAIT_TIME + 4000, 0, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 170, 2820, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 550, 2000, 0, DETECTION_THRESHOLD_CM},
  }),
  
  // GROUPIE 2
  RoadMap(PAMI_GROUPIE_2_SRF_CODE, PAMIA_COLOR::YELLOW, {
    {ROADMAP_COMMAND::CELEBRATE, SERVO_POS_LOW, SERVO_POS_HIGH, 0, SERVO_OSCILLATION_PERIOD},
    {ROADMAP_COMMAND::SET_POSITION, 280, 80, 1.57079632679, 0},
    {ROADMAP_COMMAND::WAIT, PAMI_START_WAIT_TIME + 2000, 0, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 280, 180, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 650, 1000, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 650, 1400, 0, DETECTION_THRESHOLD_CM},
  }),
  RoadMap(PAMI_GROUPIE_2_SRF_CODE, PAMIA_COLOR::BLUE, {
    {ROADMAP_COMMAND::CELEBRATE, SERVO_POS_LOW, SERVO_POS_HIGH, 0, SERVO_OSCILLATION_PERIOD},
    {ROADMAP_COMMAND::SET_POSITION, 280, 2920, -1.57079632679, 0},
    {ROADMAP_COMMAND::WAIT, PAMI_START_WAIT_TIME + 2000, 0, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 280, 2820, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 650, 2000, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 650, 1600, 0, DETECTION_THRESHOLD_CM},
  }),
  
  // GROUPIE 3
  RoadMap(PAMI_GROUPIE_3_SRF_CODE, PAMIA_COLOR::YELLOW, {
    {ROADMAP_COMMAND::CELEBRATE, SERVO_POS_LOW, SERVO_POS_HIGH, 0, SERVO_OSCILLATION_PERIOD},
    {ROADMAP_COMMAND::SET_POSITION, 390, 80, 1.57079632679, 0},
    {ROADMAP_COMMAND::WAIT, PAMI_START_WAIT_TIME, 0, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 390, 180, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 390, 600, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 550, 1000, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 550, 1800, 0, DETECTION_THRESHOLD_CM},
  }),
  RoadMap(PAMI_GROUPIE_3_SRF_CODE, PAMIA_COLOR::BLUE, {
    {ROADMAP_COMMAND::CELEBRATE, SERVO_POS_LOW, SERVO_POS_HIGH, 0, SERVO_OSCILLATION_PERIOD},
    {ROADMAP_COMMAND::SET_POSITION, 390, 2920, -1.57079632679, 0},
    {ROADMAP_COMMAND::WAIT, PAMI_START_WAIT_TIME, 0, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 390, 2820, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 390, 2400, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 550, 2000, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 550, 1200, 0, DETECTION_THRESHOLD_CM},
  }),
  
  // STAR
  RoadMap(PAMI_STAR_SRF_CODE, PAMIA_COLOR::YELLOW, {
    {ROADMAP_COMMAND::CELEBRATE, SERVO_POS_LOW, SERVO_POS_HIGH, 0, SERVO_OSCILLATION_PERIOD},
    {ROADMAP_COMMAND::SET_POSITION, 60, 80, 1.57079632679, 0},
    {ROADMAP_COMMAND::WAIT, PAMI_START_WAIT_TIME, 0, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 60, 180, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 150, 1300, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::FACE, 2000, 1300, 0, 0},
    {ROADMAP_COMMAND::GO, -150, 0, 0, 0},
    {ROADMAP_COMMAND::SET_POSITION, 80, 1300, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 440, 1300, 0, DETECTION_THRESHOLD_CM},
  }),
  RoadMap(PAMI_STAR_SRF_CODE, PAMIA_COLOR::BLUE, {
    {ROADMAP_COMMAND::CELEBRATE, SERVO_POS_LOW, SERVO_POS_HIGH, 0, SERVO_OSCILLATION_PERIOD},
    {ROADMAP_COMMAND::SET_POSITION, 60, 2920, -1.57079632679, 0},
    {ROADMAP_COMMAND::WAIT, PAMI_START_WAIT_TIME, 0, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 60, 2820, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::GO_TO, 150, 1700, 0, DETECTION_THRESHOLD_CM},
    {ROADMAP_COMMAND::FACE, 2000, 1700, 0, 0},
    {ROADMAP_COMMAND::GO, -150, 0, 0, 0},
    {ROADMAP_COMMAND::SET_POSITION, 80, 1700, 0, 0},
    {ROADMAP_COMMAND::GO_TO, 440, 1700, 0, DETECTION_THRESHOLD_CM},
  }),
};

IODebouncer btnTirette(IO_ID_TIRETTE, IO_DEBOUNCE_PERIOD, false);
IODebouncer btnCouleur(IO_ID_COULEUR, IO_DEBOUNCE_PERIOD, false);
IODebouncer btnGpio1(IO_ID_GRPIO_1, IO_DEBOUNCE_PERIOD, false);
IODebouncer btnGpio2(IO_ID_GRPIO_2, IO_DEBOUNCE_PERIOD, false);
SRF08 srf08(0, 1000); // On ne sait pas quel SRF08 est connecté au boot : adresse 0 en attendant
Servo servo1;

PamiHardWare pamiHardware(&btnTirette, &btnCouleur, &btnGpio1, &btnGpio2, &srf08, &servo1);
TestManager testManager(&Serial, &pamiHardware);
CommandManager commandManager(&Serial, &testManager);
AsservManager asservManager(&Serial0, &Serial);
DetectionManager detectionManager(&pamiHardware);
PamIA pamiA(&Serial, &pamiHardware, &asservManager, &detectionManager, roadMaps, STOP_MOVING_MS);

void setup() {
  Serial.begin(UART_PC_SPEED);
  Serial.setTimeout(10);
  Serial0.begin(UART_NUCLEO);
  Serial0.setTimeout(10);
  servo1.attach(IO_ID_GPIO_SERVO_01);
  Wire.begin(IO_I2C_SDA, IO_I2C_SCL, 100000);

  delay(2000);
  Serial.println("Detection du SRF08 branche...");
  for (int i=0; i<roadMaps.size(); i++) {
    Wire.beginTransmission(roadMaps[i].getSrfAddress());
    if (Wire.endTransmission() == 0) {
      srf08.setAddress(roadMaps[i].getSrfAddress());
      break;
    }
  }
  if (srf08.getAddress() == 0) {
    Serial.println("SRF08 non trouve!");
  } else {
    Serial.print("SRF08 trouve : ");
    Serial.println(srf08.getAddress());
  }
}

void loop() {
  commandManager.heartBeat();
  testManager.heartBeat();
  asservManager.heartBeat();
  detectionManager.heartBeat();
  pamiA.heartBeat();
}
